name: commitlint/lint/test/build

on:
  pull_request:
    branches:
      - main
      - develop
      - demo_day

jobs:
  commitlint-lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Commit lint
        uses: wagoid/commitlint-github-action@v4
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Type check
        run: yarn type-check
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
