name: Commitlint Lint Test & Build

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  commitlint-lint-test-build:
    runs-on: size-bertha
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: OpenJDK
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '11'
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install
        run: yarn install --frozen-lockfile
      # needs to run after install
      - name: Commitlint PR title
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: printf '%s' "$TITLE" | npx commitlint
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
